# Generated by Django 4.1.1 on 2022-10-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nosotros", models.CharField(max_length=300)),
                ("descripcion", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=60)),
                ("subtitulo", models.CharField(max_length=60)),
                ("autor", models.CharField(max_length=40)),
                ("fecha", models.DateField(null=True)),
                ("cuerpo", models.CharField(max_length=3500)),
            ],
        ),
        migrations.CreateModel(
            name="Inicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
